[phases.setup]
nixPkgs = ['jdk21', 'maven']

[phases.install]
cmds = ['mvn dependency:go-offline']

[phases.build]
cmds = ['build-use-substitutes false']
cmds = ['mvn clean package -Pnative -DskipTests']

[start]
cmd = 'java -jar target/*.jar'