[phases.setup]
nixPkgs = ['jdk21', 'maven']
nixpkgsArchive = ''

[phases.install]
cmds = ['echo $(date +%s) > .buildnonce', 'mvn dependency:go-offline']

[phases.build]
cmds = ['mvn clean package -Pnative -DskipTests']

[start]
cmd = 'java -jar target/*.jar'