name: ci-native
on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/ci-native.yml"
      - "src/**"
      - "config/**"
      - "liquibase/**"
      - "docker-compose.yaml"
      - "pom.xml"
  pull_request:
    branches: [main]
  schedule:
    - cron: "15 1 * * 1"
permissions:
  packages: write
concurrency:
  group: ci-native
jobs:
  test-native:
    runs-on: ubuntu-latest
    env:
      MVN: mvn --show-version --batch-mode
    steps:
      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: "22"
          distribution: "adopt"
      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: 22
          distribution: mandrel
          version: mandrel-23.0.1.2-Final
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Check Docker Compose version
        run: docker compose version
      - name: Start Keycloak and PostgreSQL
        run: |
          docker compose up --detach keycloak postgresql
          sleep 15
      - name: Run Liquibase
        run: docker compose run --rm liquibase
      - name: Run Native Tests
        run: $MVN clean verify -Pnative

  build-native:
    if: github.ref == 'refs/heads/main'
    needs: test-native
    runs-on: ubuntu-latest
    env:
      MVN: mvn --show-version --batch-mode
    steps:
      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: "22"
          distribution: "adopt"
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and Push Native Image
        run: >-
          $MVN package -Pnative -DskipTests
          -Dquarkus.native.container-build=true
          -Dquarkus.container-image.push=true
          -Dquarkus.container-image.registry=docker.io
          -Dquarkus.container-image.group=${{ secrets.DOCKER_HUB_USERNAME }}
          -Dquarkus.container-image.name=flot-api-native
          -Dquarkus.container-image.tag=latest
          '-Dquarkus.container-image.labels."org.opencontainers.image.revision"='$GITHUB_SHA