name: Build and Deploy
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Create JWT Directory
        run: mkdir -p jwt

      - name: Setup JWT Keys
        run: |
          echo "${{ secrets.JWT_PRIVATE_KEY }}" > jwt/privateKey.pem
          echo "${{ secrets.JWT_PUBLIC_KEY }}" > jwt/publicKey.pem
          chmod 600 jwt/privateKey.pem jwt/publicKey.pem

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Version
        run: |
          echo "VERSION=$(date +'%Y%m%d').${{ github.sha }}" >> $GITHUB_ENV

      - name: Build and Push Native Image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          VERSION: ${{ env.VERSION }}
        run: |
          mvn clean package -Pnative -DskipTests \
            -Dquarkus.native.container-build=true \
            -Dquarkus.container-image.push=true \
            -Dquarkus.container-image.registry=docker.io \
            -Dquarkus.container-image.group=flot701 \
            -Dquarkus.container-image.name=flot-api \
            -Dquarkus.container-image.tag=${VERSION}

      - name: Trigger Coolify Deployment
        run: |
          curl --request GET '${{ secrets.COOLIFY_WEBHOOK }}' \
            --header 'Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}'