name: scanning

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - "src/**"
      - "pom.xml"
  schedule:
    - cron: "30 1 * * 1"

permissions:
  security-events: write

jobs:
  codeql:
    runs-on: ubuntu-latest
    steps:
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"

      - name: CodeQL init
        uses: github/codeql-action/init@v2
        with:
          languages: java

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: 'Flot-MStudio/api-core'
          token: ${{ secrets.GITH_TOKEN }}

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Compile with Maven
        run: mvn --show-version --batch-mode compile

      - name: CodeQL analyze
        uses: github/codeql-action/analyze@v2
